[app]
name = "Jevek-CBS"
port = 4500
host = "0.0.0.0"
environment = "TEST"

[network]
behind_proxy = false

[cron]
enable_cron = true

[jwt]
access_expire = 3600
refresh_expire = 7200
# refresh_expire = 604800

[pg]
connect_timeout = 8
idle_timeout = 300
acquire_timeout = 10
max = 5
min = 1
